import type { Exercise } from '@/core/types/exercise'

/**
 * 动作库数据
 * 包含常见力量训练动作的完整信息
 */
export const EXERCISE_LIBRARY: Exercise[] = [
  // ===== 胸部 =====
  {
    id: 'bench_press',
    name: '杠铃卧推',
    nameEn: 'Barbell Bench Press',
    muscleGroup: 'chest',
    equipment: 'barbell',
    category: 'compound',
    description: '最重要的胸部复合动作，同时锻炼三角肌前束和肱三头肌',
  },
  {
    id: 'incline_bench_press',
    name: '上斜杠铃卧推',
    nameEn: 'Incline Barbell Bench Press',
    muscleGroup: 'chest',
    equipment: 'barbell',
    category: 'compound',
    description: '侧重上胸部的复合推举动作',
  },
  {
    id: 'dumbbell_bench_press',
    name: '哑铃卧推',
    nameEn: 'Dumbbell Bench Press',
    muscleGroup: 'chest',
    equipment: 'dumbbell',
    category: 'compound',
    description: '活动范围更大的卧推变体，有助于发展胸肌',
  },
  {
    id: 'dumbbell_fly',
    name: '哑铃飞鸟',
    nameEn: 'Dumbbell Fly',
    muscleGroup: 'chest',
    equipment: 'dumbbell',
    category: 'isolation',
    description: '胸部孤立拉伸动作，强调胸肌收缩',
  },
  {
    id: 'cable_crossover',
    name: '绳索夹胸',
    nameEn: 'Cable Crossover',
    muscleGroup: 'chest',
    equipment: 'cable',
    category: 'isolation',
    description: '持续张力的胸部孤立动作',
  },
  {
    id: 'push_up',
    name: '俯卧撑',
    nameEn: 'Push Up',
    muscleGroup: 'chest',
    equipment: 'bodyweight',
    category: 'compound',
    description: '经典自重训练动作',
  },

  // ===== 背部 =====
  {
    id: 'deadlift',
    name: '硬拉',
    nameEn: 'Deadlift',
    muscleGroup: 'back',
    equipment: 'barbell',
    category: 'compound',
    description: '全身力量之王，锻炼整个后链',
  },
  {
    id: 'barbell_row',
    name: '杠铃划船',
    nameEn: 'Barbell Row',
    muscleGroup: 'back',
    equipment: 'barbell',
    category: 'compound',
    description: '最重要的水平拉类动作',
  },
  {
    id: 'pull_up',
    name: '引体向上',
    nameEn: 'Pull Up',
    muscleGroup: 'back',
    equipment: 'bodyweight',
    category: 'compound',
    description: '上背部和背阔肌的最佳自重训练',
  },
  {
    id: 'lat_pulldown',
    name: '高位下拉',
    nameEn: 'Lat Pulldown',
    muscleGroup: 'back',
    equipment: 'cable',
    category: 'compound',
    description: '引体向上的替代动作，适合不同水平训练者',
  },
  {
    id: 'cable_row',
    name: '坐姿绳索划船',
    nameEn: 'Seated Cable Row',
    muscleGroup: 'back',
    equipment: 'cable',
    category: 'compound',
    description: '中等强度水平拉类动作',
  },
  {
    id: 't_bar_row',
    name: 'T杠划船',
    nameEn: 'T-Bar Row',
    muscleGroup: 'back',
    equipment: 'barbell',
    category: 'compound',
    description: '大重量划船变体',
  },

  // ===== 肩部 =====
  {
    id: 'overhead_press',
    name: '杠铃推举',
    nameEn: 'Overhead Press',
    muscleGroup: 'shoulders',
    equipment: 'barbell',
    category: 'compound',
    description: '最重要的肩部复合动作',
  },
  {
    id: 'dumbbell_shoulder_press',
    name: '哑铃推举',
    nameEn: 'Dumbbell Shoulder Press',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    category: 'compound',
    description: '活动范围更大的肩部推举',
  },
  {
    id: 'lateral_raise',
    name: '侧平举',
    nameEn: 'Lateral Raise',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    category: 'isolation',
    description: '三角肌中束的孤立训练',
  },
  {
    id: 'face_pull',
    name: '面拉',
    nameEn: 'Face Pull',
    muscleGroup: 'shoulders',
    equipment: 'cable',
    category: 'accessory',
    description: '后三角肌和上背部的康复/预防动作',
  },
  {
    id: 'reverse_fly',
    name: '反向飞鸟',
    nameEn: 'Reverse Fly',
    muscleGroup: 'shoulders',
    equipment: 'dumbbell',
    category: 'isolation',
    description: '后三角肌孤立动作',
  },

  // ===== 肱二头肌 =====
  {
    id: 'barbell_curl',
    name: '杠铃弯举',
    nameEn: 'Barbell Curl',
    muscleGroup: 'biceps',
    equipment: 'barbell',
    category: 'isolation',
    description: '肱二头肌基础训练',
  },
  {
    id: 'dumbbell_curl',
    name: '哑铃弯举',
    nameEn: 'Dumbbell Curl',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    category: 'isolation',
    description: '允许交替训练的弯举变体',
  },
  {
    id: 'hammer_curl',
    name: '锤式弯举',
    nameEn: 'Hammer Curl',
    muscleGroup: 'biceps',
    equipment: 'dumbbell',
    category: 'isolation',
    description: '同时锻炼肱桡肌的弯举变体',
  },

  // ===== 肱三头肌 =====
  {
    id: 'close_grip_bench',
    name: '窄距卧推',
    nameEn: 'Close Grip Bench Press',
    muscleGroup: 'triceps',
    equipment: 'barbell',
    category: 'compound',
    description: '侧重肱三头肌的卧推变体',
  },
  {
    id: 'tricep_pushdown',
    name: '三头下压',
    nameEn: 'Tricep Pushdown',
    muscleGroup: 'triceps',
    equipment: 'cable',
    category: 'isolation',
    description: '肱三头肌经典孤立动作',
  },
  {
    id: 'overhead_tricep_extension',
    name: '过头臂屈伸',
    nameEn: 'Overhead Tricep Extension',
    muscleGroup: 'triceps',
    equipment: 'dumbbell',
    category: 'isolation',
    description: '侧重长头的三头肌训练',
  },

  // ===== 股四头肌 =====
  {
    id: 'squat',
    name: '深蹲',
    nameEn: 'Barbell Back Squat',
    muscleGroup: 'quads',
    equipment: 'barbell',
    category: 'compound',
    description: '力量训练之王，全面发展下肢力量',
  },
  {
    id: 'front_squat',
    name: '前蹲',
    nameEn: 'Front Squat',
    muscleGroup: 'quads',
    equipment: 'barbell',
    category: 'compound',
    description: '更侧重股四头肌的深蹲变体',
  },
  {
    id: 'leg_press',
    name: '腿举',
    nameEn: 'Leg Press',
    muscleGroup: 'quads',
    equipment: 'machine',
    category: 'compound',
    description: '安全的大重量下肢训练',
  },
  {
    id: 'leg_extension',
    name: '腿屈伸',
    nameEn: 'Leg Extension',
    muscleGroup: 'quads',
    equipment: 'machine',
    category: 'isolation',
    description: '股四头肌孤立训练',
  },
  {
    id: 'hack_squat',
    name: '哈克深蹲',
    nameEn: 'Hack Squat',
    muscleGroup: 'quads',
    equipment: 'machine',
    category: 'compound',
    description: '固定轨迹的深蹲变体',
  },

  // ===== 腘绳肌 =====
  {
    id: 'romanian_deadlift',
    name: '罗马尼亚硬拉',
    nameEn: 'Romanian Deadlift',
    muscleGroup: 'hamstrings',
    equipment: 'barbell',
    category: 'compound',
    description: '腘绳肌和臀肌的最佳训练之一',
  },
  {
    id: 'leg_curl',
    name: '腿弯举',
    nameEn: 'Leg Curl',
    muscleGroup: 'hamstrings',
    equipment: 'machine',
    category: 'isolation',
    description: '腘绳肌孤立训练',
  },
  {
    id: 'nordic_hamstring_curl',
    name: '北欧腘绳肌弯举',
    nameEn: 'Nordic Hamstring Curl',
    muscleGroup: 'hamstrings',
    equipment: 'bodyweight',
    category: 'isolation',
    description: '高效的腘绳肌离心训练',
  },

  // ===== 臀肌 =====
  {
    id: 'hip_thrust',
    name: '臀推',
    nameEn: 'Hip Thrust',
    muscleGroup: 'glutes',
    equipment: 'barbell',
    category: 'compound',
    description: '臀部最佳训练动作',
  },
  {
    id: 'bulgarian_split_squat',
    name: '保加利亚分腿蹲',
    nameEn: 'Bulgarian Split Squat',
    muscleGroup: 'glutes',
    equipment: 'dumbbell',
    category: 'compound',
    description: '单侧下肢训练，同时锻炼臀肌和股四头肌',
  },
  {
    id: 'cable_kickback',
    name: '绳索后踢',
    nameEn: 'Cable Kickback',
    muscleGroup: 'glutes',
    equipment: 'cable',
    category: 'isolation',
    description: '臀部孤立训练',
  },

  // ===== 小腿 =====
  {
    id: 'calf_raise',
    name: '提踵',
    nameEn: 'Calf Raise',
    muscleGroup: 'calves',
    equipment: 'machine',
    category: 'isolation',
    description: '小腿肌群基础训练',
  },

  // ===== 腹肌 =====
  {
    id: 'plank',
    name: '平板支撑',
    nameEn: 'Plank',
    muscleGroup: 'abs',
    equipment: 'bodyweight',
    category: 'isolation',
    description: '核心稳定性训练',
  },
  {
    id: 'cable_crunch',
    name: '绳索卷腹',
    nameEn: 'Cable Crunch',
    muscleGroup: 'abs',
    equipment: 'cable',
    category: 'isolation',
    description: '负重腹肌训练',
  },
  {
    id: 'hanging_leg_raise',
    name: '悬垂举腿',
    nameEn: 'Hanging Leg Raise',
    muscleGroup: 'abs',
    equipment: 'bodyweight',
    category: 'isolation',
    description: '下腹部强化训练',
  },

  // ===== 前臂 =====
  {
    id: 'wrist_curl',
    name: '腕弯举',
    nameEn: 'Wrist Curl',
    muscleGroup: 'forearms',
    equipment: 'dumbbell',
    category: 'isolation',
    description: '前臂屈肌训练',
  },

  // ===== 斜方肌 =====
  {
    id: 'shrug',
    name: '耸肩',
    nameEn: 'Shrug',
    muscleGroup: 'traps',
    equipment: 'barbell',
    category: 'isolation',
    description: '斜方肌上束基础训练',
  },
  {
    id: 'farmer_walk',
    name: '农夫行走',
    nameEn: 'Farmer Walk',
    muscleGroup: 'traps',
    equipment: 'dumbbell',
    category: 'accessory',
    description: '全身功能性训练，同时锻炼握力和斜方肌',
  },
]